### ISSUE TITLE
Front-end issues

### ISSUE THREAD

**Issue by Prabhmeetchef** [atominfra/landing-page#32]
- [ ] Glitch: The hero section text is inconsistent (when page is loaded initially the size is small but reverts to normal in 1-2s).

https://github.com/user-attachments/assets/e045c360-143c-4784-b3ec-7f4c8ec77d9c

**Comment by Prabhmeetchef** [comment]
- [ ] In Mobile version. Remove the dark border present on the hamburger menu.

![WhatsApp Image 2024-11-18 at 3 33 42 PM](https://github.com/user-attachments/assets/9bdfcaf3-9c43-4392-b2f2-a844f1b98b12)

**Comment by Shryansh107** [comment]
both issues have been fixed in v0-dev
