### ISSUE TITLE
Design Features Section

### ISSUE THREAD

**Issue by singhalkarun** [atominfra/landing-page#6]
#### Description

Create a features section and highlight below features

Unified - All in one tool for Building, Training, Packaging, Deploying, Monitoring and Auto scaling AI.
Portable - Seamless migration from one provider to another be it cloud or to your own hardware, enabling you to choose the most cost-effective provider.
Built for AI Engineers - Allows to auto package and deploy a jupyter notebook abstracting out all the boring tough stuff.
Built for Efficiency - We auto distribute load among CPU and GPU and serve it to you in a single API.

**Comment by Prabhmeetchef** [comment]
Design for both dark and Light mode ready, please verify @singhalkarun.
